export const codes = {
  dataRetrievedSuccessfully: {
    code: 'DATA_RETRIEVED_SUCCESSFULLY',
    message: 'The data has been successfully retrieved.',
  },
  retrievingDataError: {
    code: 'RETRIEVING_DATA_ERROR',
    message: 'There was an issue retrieving the data.',
  },
  dataSavedSuccessfully: {
    code: 'DATA_SAVED_SUCCESSFULLY',
    message: 'The data has been successfully saved.',
  },
  savingDataError: {
    code: 'SAVING_DATA_ERROR',
    message: 'There was an issue saving the data.',
  },
  dataUpdatedSuccessfully: {
    code: 'DATA_UPDATED_SUCCESSFULLY',
    message: 'The data has been successfully updated.',
  },
  updatingDataError: {
    code: 'UPDATING_DATA_ERROR',
    message: 'There was an issue updating the data.',
  },
  dataDeletedSuccessfully: {
    code: 'DATA_DELETED_SUCCESSFULLY',
    message: 'The data has been successfully deleted.',
  },
  deletingDataError: {
    code: 'DELETING_DATA_ERROR',
    message: 'There was an issue deleting the data.',
  },
  noDataFound: {
    code: 'NO_DATA_FOUND',
    message: 'No data was found.',
  },
  badRequest: {
    code: 'BAD_REQUEST',
    message: 'There was an issue with your request.',
  },
  startError: {
    code: 'START_ERROR',
    message: 'There was an issue starting the application.',
  },
  unhandledError: {
    code: 'UNHANDLED_ERROR',
    message: 'An unexpected error occurred.',
  },
  conflictRequest: {
    code: 'CONFLICT_REQUEST',
    message: 'The request could not be completed due to a conflict.',
  },
  unauthorizedRequest: {
    code: 'UNAUTHORIZED_REQUEST',
    message:
      'The request could not be completed due to a lack of authorization.',
  },
  logginSuccess: {
    code: 'LOGGIN_SUCCESS',
    message: 'The user has successfully logged in.',
  },
};
